[project]
name = "lapelicula"
version = "0.0.1"
authors = [{ name = "Alexandr Gilevich" }]
requires-python = ">=3.11,<=3.13"
dependencies = [
    "databricks-sdk~=0.73.0",
    "dependency-injector~=4.48.3",
    "keras~=3.12.0",
    "kmedoids==0.5.3.1",
    # Any dependencies for jobs and pipelines in this project can be added here
    # See also https://docs.databricks.com/dev-tools/bundles/library-dependencies
    #
    # LIMITATION: for pipelines, dependencies are cached during development;
    # add dependencies to the 'environment' section of your pipeline.yml file instead
    "mlflow~=3.8.0",
    "mlflow-skinny~=3.8.0",
    "numpy~=1.26.4",
    "pandas~=2.3.3",
    "pandas-stubs==2.3.2.250926",
    "pydantic~=2.12.4",
    "pyspark==4.0.1",
    "requests~=2.32.5",
    "scikit-learn==1.7.0",
    "scipy~=1.16.3",
    "tabulate==0.9.0",
    "tensorflow==2.16.2",
]

[dependency-groups]
dev = [
    "pytest",
    "databricks-dlt",
#    "databricks-connect>=15.4,<17.0",
    "databricks-bundles==0.277.0",
]

[project.scripts]
#main = "aaaa.main:main"

#[build-system]
#requires = ["hatchling"]
#build-backend = "hatchling.build"

[tool.black]
line-length = 125
